/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.9 and Signal Processing Toolbox 8.5.
 * Generated on: 19-Oct-2021 20:02:45
 */

/*
 * Discrete-Time FIR Filter (real)
 * -------------------------------
 * Filter Structure  : Direct-Form FIR
 * Filter Length     : 31
 * Stable            : Yes
 * Linear Phase      : Yes (Type 1)
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * C:\Program Files\MATLAB\R2020b\extern\include\tmwtypes.h 
 */
const int BL = 31;
const real64_T B[31] = {
   -0.03928569141863, -0.04209698304048, -0.03306544563932, -0.01663023572165,
  -0.002245081324707,                 0, -0.01515177858799,  -0.0442421546351,
   -0.07500656587427, -0.09064389002592, -0.07694287806338, -0.02923131710569,
    0.04408499181657,   0.1233101812438,   0.1841963215111,   0.2070140922819,
     0.1841963215111,   0.1233101812438,  0.04408499181657, -0.02923131710569,
   -0.07694287806338, -0.09064389002592, -0.07500656587427,  -0.0442421546351,
   -0.01515177858799,                 0,-0.002245081324707, -0.01663023572165,
   -0.03306544563932, -0.04209698304048, -0.03928569141863
};
